### ISSUE TITLE
您好。请问能给一个代码的运行说明吗？我这里gcc下运行有错误。

### ISSUE THREAD

**Issue by boboIqiqi** [Federico2014/SM9#1]
@Federico2014 大侠，您好。有些问题想请教一下。

工程中的文件后缀是 sm9.vcxproj，直接用visual studio 2019 community也无法打开。支持的文件类型只有：
- *.sln
- *.dsw
- *.vcw
- *.slnf

我编写Makefile，将其运行在Linux gcc下面，（由于输出中文都是乱码，将提示修改成了英文）。输出的大数结果，为乱码。且最终加密解密验证的结果为 failed。
```
all:
      gcc *.c -o main -lm
```
<img width="590" alt="输出结果" src="https://user-images.githubusercontent.com/1284515/79289828-fbd32a80-7efc-11ea-9b0f-70fce47e658c.png">

**Comment by Federico2014** [comment]
> @Federico2014 大侠，您好。有些问题想请教一下。
> 
> 工程中的文件后缀是 sm9.vcxproj，直接用visual studio 2019 community也无法打开。支持的文件类型只有：
> 
> * *.sln
> * *.dsw
> * *.vcw
> * *.slnf
> 
> 我编写Makefile，将其运行在Linux gcc下面，（由于输出中文都是乱码，将提示修改成了英文）。输出的大数结果，为乱码。且最终加密解密验证的结果为 failed。
> 
> ```
> all:
>       gcc *.c -o main -lm
> ```
> 
> <img alt="输出结果" width="590" src="https://user-images.githubusercontent.com/1284515/79289828-fbd32a80-7efc-11ea-9b0f-70fce47e658c.png">

这个是我以前在visual studio下开发的，也没在gcc运行过，你先在vs新建一个工程，把这些代码加进去就行了

**Comment by zjhzzz** [comment]
您好，请问您编译SM9代码成功了吗 @boboIqiqi
